###############################################
# custom settings (like title and logo) go here

header_title: "Cookiaria Website"
custom_logo: "/assets/glungus.png"
footer_text: ""

####################################
# pfp updated thing with credit :333

pfp_credit: false
pfp_link: "https://cdn.discordapp.com/avatars/698379761805819975/9e697764fbdc90f9b9035fee45f4454b.webp?size=4096"
pfp_artist_link: "null"
pfp_artist_at: "null"
pfpacolor: "#2db67e"

comments_toggle: true

##############################
# default discord embed things 

accent_color: "#FF8600"
embed_description: "check out my Cool Website"
large_image: true
embed_image: https://cookiaria.xyz/assets/embed_banner.png


#############################
# dont touch or it will break (this is held together with ducktape)

excerpt_separator: <!--bungus-->

markdown: kramdown
highlighter: rouge

collections: 
  things:
    output: true
    permalink: /post/:name
  changelog:
    output: true
    permalink: /changelog/:name


