###############################################
# custom settings (like title and logo) go here

header_title: Cookiaria Website
custom_logo: /assets/glungus.png
footer_text: 

comments_toggle: true

pfp_link: https://cdn.discordapp.com/avatars/698379761805819975/7661d5f805f0fd447120c79e28d87d8b.webp?size=4096
pfp_artist_link: https://twitter.com/cookiaria
pfp_artist_at: "meeee :3"
pfpacolor: fd8064

###################################################################
# dont touch or it will break (this is held together with ducktape)

markdown: kramdown
highlighter: rouge

didyouactuallyfinishthis: false

collections: 
  things:
    output: true
    permalink: /post/:name
  changelog:
    output: true
    permalink: /changelog/:name


